# Generated by Django 4.2 on 2024-03-26 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('url_slug', models.SlugField(unique=True)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('stock_quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Variant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size_medi', models.CharField(max_length=20)),
                ('medi_quantity', models.PositiveSmallIntegerField()),
                ('price', models.FloatField()),
                ('stock_quantity', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product_category'),
        ),
    ]
