# Generated by Django 4.2 on 2024-05-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_rename_size_medi_product_variant_size_medi_mg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url_slug',
            field=models.SlugField(null=True),
        ),
    ]
