# Generated by Django 4.2 on 2024-05-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_product_url_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prescription',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
    ]
