# Generated by Django 4.2 on 2024-05-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopowner',
            name='shop_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopowner',
            name='phone_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
