# Generated by Django 4.2 on 2024-05-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_shopowner_shop_name_alter_shopowner_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopowner',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
