# Generated by Django 4.2 on 2024-05-21 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_alter_shopowner_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopowner',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shopowner',
            name='full_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopowner',
            name='pin_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
