# Generated by Django 4.2 on 2024-05-21 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Shop', '0004_alter_shopowner_city_alter_shopowner_full_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopowner',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
