# Generated by Django 4.2 on 2024-03-26 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
                ('product_variant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product_variant')),
            ],
        ),
    ]
