# Generated by Django 4.2 on 2024-04-10 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
        ('Cart', '0002_carts_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='carts',
            name='product_variant_id',
        ),
        migrations.RemoveField(
            model_name='carts',
            name='quantity',
        ),
        migrations.AddField(
            model_name='carts',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='carts',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='Cart.carts')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.product')),
                ('product_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.product_variant')),
            ],
        ),
    ]
