# Generated by Django 4.2 on 2024-03-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(max_length=255)),
                ('phone_number', models.BigIntegerField()),
                ('specialisation', models.CharField(max_length=255)),
                ('experience', models.IntegerField()),
                ('schedule_time', models.DateTimeField()),
                ('clinic_name', models.CharField(max_length=255)),
                ('clinic_address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=20)),
            ],
        ),
    ]
