# Generated by Django 4.2 on 2024-03-28 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('Appointment_id', models.AutoField(primary_key=True, serialize=False)),
                ('Appointment_Date', models.DateTimeField()),
                ('Appointment_time', models.TimeField()),
                ('Doctor_pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctor')),
            ],
        ),
    ]
