# Generated by Django 4.2 on 2024-05-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0005_alter_doctor_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_image',
            field=models.ImageField(null=True, upload_to='doctor_image'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='pin_code',
            field=models.CharField(default='481001', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='schedule_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
