# Generated by Django 4.2 on 2024-05-25 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Doctor', '0006_alter_doctor_doctor_image_alter_doctor_pin_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='Number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
