# Generated by Django 4.2 on 2024-05-25 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0007_appointment_name_appointment_number_appointment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Doctor_pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctor'),
        ),
    ]
