# Generated by Django 4.2 on 2024-05-27 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0010_alter_appointment_doctor_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='Doctor_pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctor'),
        ),
    ]
