# Generated by Django 4.2 on 2024-03-26 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping_addresses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.orders')),
            ],
        ),
    ]
