# Generated by Django 4.2 on 2024-03-26 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('total_amount', models.FloatField(default=1500)),
                ('discount_amount', models.FloatField(default=100)),
                ('gross_amount', models.FloatField(default=1400)),
                ('shipping_amount', models.FloatField(default=50)),
                ('net_amount', models.FloatField(default=1450)),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('processing', 'Processing'), ('shipping', 'Shipping'), ('delivered', 'Delivered')], max_length=20)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('not_paid', 'Not Paid')], max_length=20)),
                ('payment_type', models.CharField(choices=[('net_banking', 'Net Banking'), ('upi', 'UPI'), ('cash_on_delivery', 'Cash on Delivery')], max_length=20)),
                ('payment_transaction_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=50, null=True)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('total_amount', models.FloatField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.orders')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
                ('product_variant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product_variant')),
            ],
        ),
    ]
